name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
          
      - name: Install Android NDK
        run: |
          sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleRelease
        
      - name: Build Module Zip
        run: ./gradlew makeModule
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: module-zip
          path: build/outputs/module/*.zip
          
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: module-zip
          path: module-zip
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: module-zip/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
