name: Build and Release Module

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up build environment
        run: |
          mkdir -p build/outputs/module
          
      - name: Create module zip
        run: |
          zip -r build/outputs/module/monet-theming-bridge.zip \
            README.md \
            LICENSE \
            module.prop \
            install.sh \
            src/ \
            web/ \
            examples/ \
            docs/
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: module-zip
          path: build/outputs/module/*.zip
          
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: module-zip
          path: module-zip
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: module-zip/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
