/**
 * Monet Theming Bridge for Web UIs
 * 
 * This JavaScript library provides access to Android's Monet theming colors
 * for web UIs running in sandboxed environments.
 */

class MonetBridge {
    constructor(options = {}) {
        this.options = {
            colorFilePath: '/data/local/tmp/monet_colors.json',
            refreshInterval: options.refreshInterval || 30000, // 30 seconds by default
            onColorsLoaded: options.onColorsLoaded || null,
            onError: options.onError || null,
            fallbackColors: options.fallbackColors || this._getDefaultFallbackColors()
        };
        
        this.colors = { ...this.options.fallbackColors };
        this.isLoading = false;
        this.intervalId = null;
    }
    
    /**
     * Initialize the Monet Bridge and load colors
     */
    async init() {
        try {
            await this.loadColors();
            
            // Set up periodic refresh
            if (this.options.refreshInterval > 0) {
                this.intervalId = setInterval(() => {
                    this.loadColors();
                }, this.options.refreshInterval);
            }
            
            return true;
        } catch (error) {
            console.error('Failed to initialize MonetBridge:', error);
            if (this.options.onError) {
                this.options.onError(error);
            }
            return false;
        }
    }
    
    /**
     * Load Monet colors from the file generated by the native module
     */
    async loadColors() {
        if (this.isLoading) return;
        
        this.isLoading = true;
        
        try {
            const response = await fetch(this.options.colorFilePath);
            
            if (!response.ok) {
                throw new Error(`Failed to load colors: ${response.status} ${response.statusText}`);
            }
            
            const data = await response.json();
            
            // Update colors
            this.colors = { ...this.options.fallbackColors, ...data };
            
            // Notify callback if provided
            if (this.options.onColorsLoaded) {
                this.options.onColorsLoaded(this.colors);
            }
            
            console.log('Monet colors loaded successfully');
            
            // Apply colors to CSS variables if requested
            if (this.options.applyToCssVars) {
                this.applyColorsToCssVariables();
            }
            
            return this.colors;
        } catch (error) {
            console.error('Error loading Monet colors:', error);
            if (this.options.onError) {
                this.options.onError(error);
            }
        } finally {
            this.isLoading = false;
        }
    }
    
    /**
     * Get a specific Monet color by name
     */
    getColor(name) {
        return this.colors[name] || this.options.fallbackColors[name] || null;
    }
    
    /**
     * Get all available Monet colors
     */
    getAllColors() {
        return { ...this.colors };
    }
    
    /**
     * Apply Monet colors to CSS variables
     */
    applyColorsToCssVariables(prefix = '--monet-') {
        const root = document.documentElement;
        
        Object.entries(this.colors).forEach(([name, value]) => {
            root.style.setProperty(`${prefix}${name}`, value);
        });
    }
    
    /**
     * Clean up resources
     */
    destroy() {
        if (this.intervalId) {
            clearInterval(this.intervalId);
            this.intervalId = null;
        }
    }
    
    /**
     * Get default fallback colors (Material You-like palette)
     */
    _getDefaultFallbackColors() {
        return {
            "accent1_10": "#000000",
            "accent1_50": "#6750A4",
            "accent1_100": "#B69DF8",
            "accent1_200": "#EADDFF",
            "accent1_300": "#D0BCFF",
            "accent1_400": "#B69DF8",
            "accent1_500": "#9A82DB",
            "accent1_600": "#7F67BE",
            "accent1_700": "#6750A4",
            "accent1_800": "#4F378B",
            "accent1_900": "#381E72",
            "accent2_10": "#291800",
            "accent2_50": "#9C4146",
            "accent2_100": "#FFB4AB"
        };
    }
}

// Export for CommonJS and ES modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = MonetBridge;
} else if (typeof define === 'function' && define.amd) {
    define([], function() { return MonetBridge; });
} else {
    window.MonetBridge = MonetBridge;
}
